name: Check Flakes

on:
  pull_request_target:
    types:
      - opened
      - auto_merge_enabled
  push:
    paths:
      - nixos/**
      - flake.nix
      - flake.lock

jobs:
  check_flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check