name: Check Flakes

on:
  pull_request_target:
    types:
      - opened
      - auto_merge_enabled
  push:
    paths:
      - nixos/**
      - flake.nix
      - flake.lock

jobs:
  check_flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check