name: Check Flakes

on:
  pull_request_target:
    types:
      - opened
      - auto_merge_enabled
  push:
    paths:
      - nixos/**
      - flake.nix
      - flake.lock

jobs:
  check_flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: cachix/install-nix-action@9f70348d77d0422624097c4b7a75563948901306 # v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check